plugins {
    id 'com.android.application'
}

android {
    namespace 'org.n0pocketworkstation.pckeyboard'
    //noinspection GradleDependency
    compileSdk 35
    ndkVersion "28.2.13676358"



    defaultConfig {
        applicationId "org.n0pocketworkstation.pckeyboard"
        minSdk 23
        //noinspection OldTargetApi
        targetSdk 34
        //noinspection TargetApi

        versionCode 1041004
        versionName "1.41.1-4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }

    buildFeatures {
        buildConfig true
    }    // debug option - to remove  14.04.2026 16:11     //tasks.withType(JavaCompile).configureEach {options.compilerArgs << "-Xlint:deprecation" << "-Xlint:unchecked"}
 }

dependencies {
    implementation libs.kotlin.stdlib
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.preference


    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}